#pragma checksum "..\..\Window1.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "12072B8EF6FB5E866696F2E456C6FB8A81D0839C867D1CA0C4012776CB37CD0B"
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AufgabenPlaner {
    
    
    /// <summary>
    /// Window1
    /// </summary>
    public partial class Window1 : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 69 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_todos;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_newTodo;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_end;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label HeaderLabel;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dg_todos;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border NewTodoPanel;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel stack_newTodo;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbx_newTodo_title;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbx_newTodo_description;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dp_newTodo_datePicker;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_newToDo_Green;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_newToDo_Orange;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_newToDo_Red;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_newTodo_Clear;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\Window1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_new_Todo_Save;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/AufgabenPlaner;component/window1.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Window1.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 5 "..\..\Window1.xaml"
            ((AufgabenPlaner.Window1)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btn_todos = ((System.Windows.Controls.Button)(target));
            
            #line 69 "..\..\Window1.xaml"
            this.btn_todos.Click += new System.Windows.RoutedEventHandler(this.MainButtons_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btn_newTodo = ((System.Windows.Controls.Button)(target));
            
            #line 70 "..\..\Window1.xaml"
            this.btn_newTodo.Click += new System.Windows.RoutedEventHandler(this.MainButtons_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btn_end = ((System.Windows.Controls.Button)(target));
            
            #line 71 "..\..\Window1.xaml"
            this.btn_end.Click += new System.Windows.RoutedEventHandler(this.MainButtons_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.HeaderLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.dg_todos = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 7:
            
            #line 101 "..\..\Window1.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Btn_Delete_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 102 "..\..\Window1.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Btn_Complete_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.NewTodoPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 10:
            this.stack_newTodo = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 11:
            this.tbx_newTodo_title = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.tbx_newTodo_description = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.dp_newTodo_datePicker = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 14:
            this.rb_newToDo_Green = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 15:
            this.rb_newToDo_Orange = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 16:
            this.rb_newToDo_Red = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 17:
            this.btn_newTodo_Clear = ((System.Windows.Controls.Button)(target));
            
            #line 122 "..\..\Window1.xaml"
            this.btn_newTodo_Clear.Click += new System.Windows.RoutedEventHandler(this.Btn_NewTodo_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.btn_new_Todo_Save = ((System.Windows.Controls.Button)(target));
            
            #line 123 "..\..\Window1.xaml"
            this.btn_new_Todo_Save.Click += new System.Windows.RoutedEventHandler(this.Btn_NewTodo_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

